// Hand-written row types + a Database type that layers the memberships tables
// onto the generated Supabase types.
//
// The generated `integrations/supabase/types.ts` is regenerated by Lovable and
// does not yet know about `membership_plans`, `memberships` or
// `bank_transactions`, so `client.from("memberships")` would not type-check. We
// don't hand-edit the generated file (it's auto-generated); instead we describe
// the new tables here and cast the shared clients to `MembershipClient` inside
// the server functions. Once Lovable regenerates the types, these definitions
// can be dropped in favour of the generated ones.
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";
import type { MembershipPlanKind, MembershipStatus } from "@/lib/validation";

export type MembershipPlanRow = {
  id: string;
  code: string;
  name: string;
  description: string | null;
  kind: MembershipPlanKind;
  public_price_cents: number;
  student_price_cents: number | null;
  duration_days: number | null;
  session_credits: number | null;
  is_active: boolean;
  sort_order: number;
  created_at: string;
};

export type MembershipRow = {
  id: string;
  user_id: string | null;
  plan_id: string;
  status: MembershipStatus;
  is_student: boolean;
  uts_student_number: string | null;
  price_cents: number;
  payment_reference: string;
  payment_method: "bank_transfer" | "stripe" | "manual";
  paid_at: string | null;
  starts_at: string | null;
  ends_at: string | null;
  sessions_remaining: number | null;
  session_date: string | null;
  notes: string | null;
  created_at: string;
};

export type BankTransactionRow = {
  id: string;
  import_batch: string;
  posted_at: string | null;
  amount_cents: number;
  description: string;
  reference: string | null;
  raw: unknown;
  dedupe_hash: string;
  matched_membership_id: string | null;
  matched_at: string | null;
  matched_by: string | null;
  status: "unmatched" | "matched" | "ignored";
  created_at: string;
};

export type ClubSettingRow = {
  key: string;
  value: string;
  updated_at: string;
  updated_by: string | null;
};

// Loose Insert/Update: the server functions build explicit literal objects, so a
// permissive partial shape is enough to satisfy the Supabase client generics.
type TableDef<Row> = { Row: Row; Insert: Partial<Row>; Update: Partial<Row>; Relationships: [] };

type MembershipTables = {
  membership_plans: TableDef<MembershipPlanRow>;
  memberships: TableDef<MembershipRow>;
  bank_transactions: TableDef<BankTransactionRow>;
  club_settings: TableDef<ClubSettingRow>;
};

/** The generated Database, with the memberships tables layered into `public`. */
export type MembershipDatabase = Omit<Database, "public"> & {
  public: Omit<Database["public"], "Tables"> & {
    Tables: Database["public"]["Tables"] & MembershipTables;
  };
};

export type MembershipClient = SupabaseClient<MembershipDatabase>;
