/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as CodeOfConductRouteImport } from './routes/code-of-conduct'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FirstClassRouteImport } from './routes/first-class'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as KbRouteRouteImport } from './routes/kb/route'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterInterestRouteImport } from './routes/register-interest'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as WaiverRouteImport } from './routes/waiver'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedMembershipRouteImport } from './routes/_authenticated/membership'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as KbIndexRouteImport } from './routes/kb/index'
import { Route as KbSlugRouteImport } from './routes/kb/$slug'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager.index'
import { Route as AuthenticatedManagerApiTokensRouteImport } from './routes/_authenticated/manager.api-tokens'
import { Route as AuthenticatedManagerBlogRouteImport } from './routes/_authenticated/manager.blog'
import { Route as AuthenticatedManagerBlogCommentsRouteImport } from './routes/_authenticated/manager.blog-comments'
import { Route as AuthenticatedManagerCalendarRouteImport } from './routes/_authenticated/manager.calendar'
import { Route as AuthenticatedManagerCheckInRouteImport } from './routes/_authenticated/manager.check-in'
import { Route as AuthenticatedManagerKbRouteImport } from './routes/_authenticated/manager.kb'
import { Route as AuthenticatedManagerMembershipPlansRouteImport } from './routes/_authenticated/manager.membership-plans'
import { Route as AuthenticatedManagerMembershipsRouteImport } from './routes/_authenticated/manager.memberships'
import { Route as AuthenticatedManagerReconciliationRouteImport } from './routes/_authenticated/manager.reconciliation'
import { Route as AuthenticatedManagerSettingsRouteImport } from './routes/_authenticated/manager.settings'
import { Route as AuthenticatedManagerUsersRouteImport } from './routes/_authenticated/manager.users'
import { Route as AuthenticatedManagerWaiverTemplateRouteImport } from './routes/_authenticated/manager.waiver-template'
import { Route as AuthenticatedManagerWaiversRouteImport } from './routes/_authenticated/manager.waivers'
import { Route as ApiCalendarTokenRouteImport } from './routes/api/calendar/$token'
import { Route as ApiManagerAgentRouteImport } from './routes/api/manager/agent'
import { Route as ApiVerifyEmailTokenRouteImport } from './routes/api/verify-email/$token'
import { Route as AuthenticatedManagerBlogIdRouteImport } from './routes/_authenticated/manager.blog_.$id'
import { Route as AuthenticatedManagerBlogNewRouteImport } from './routes/_authenticated/manager.blog_.new'
import { Route as AuthenticatedManagerUsersUserIdRouteImport } from './routes/_authenticated/manager.users_.$userId'
import { Route as AuthenticatedManagerWaiversUploadRouteImport } from './routes/_authenticated/manager.waivers_.upload'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeOfConductRoute = CodeOfConductRouteImport.update({
  id: '/code-of-conduct',
  path: '/code-of-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstClassRoute = FirstClassRouteImport.update({
  id: '/first-class',
  path: '/first-class',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const KbRouteRoute = KbRouteRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterInterestRoute = RegisterInterestRouteImport.update({
  id: '/register-interest',
  path: '/register-interest',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiverRoute = WaiverRouteImport.update({
  id: '/waiver',
  path: '/waiver',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembershipRoute = AuthenticatedMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KbIndexRoute = KbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KbRouteRoute,
} as any)
const KbSlugRoute = KbSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KbRouteRoute,
} as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/manager/',
    path: '/manager/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerApiTokensRoute =
  AuthenticatedManagerApiTokensRouteImport.update({
    id: '/manager/api-tokens',
    path: '/manager/api-tokens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerBlogRoute =
  AuthenticatedManagerBlogRouteImport.update({
    id: '/manager/blog',
    path: '/manager/blog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerBlogCommentsRoute =
  AuthenticatedManagerBlogCommentsRouteImport.update({
    id: '/manager/blog-comments',
    path: '/manager/blog-comments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerCalendarRoute =
  AuthenticatedManagerCalendarRouteImport.update({
    id: '/manager/calendar',
    path: '/manager/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerCheckInRoute =
  AuthenticatedManagerCheckInRouteImport.update({
    id: '/manager/check-in',
    path: '/manager/check-in',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerKbRoute = AuthenticatedManagerKbRouteImport.update({
  id: '/manager/kb',
  path: '/manager/kb',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagerMembershipPlansRoute =
  AuthenticatedManagerMembershipPlansRouteImport.update({
    id: '/manager/membership-plans',
    path: '/manager/membership-plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerMembershipsRoute =
  AuthenticatedManagerMembershipsRouteImport.update({
    id: '/manager/memberships',
    path: '/manager/memberships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerReconciliationRoute =
  AuthenticatedManagerReconciliationRouteImport.update({
    id: '/manager/reconciliation',
    path: '/manager/reconciliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerSettingsRoute =
  AuthenticatedManagerSettingsRouteImport.update({
    id: '/manager/settings',
    path: '/manager/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerUsersRoute =
  AuthenticatedManagerUsersRouteImport.update({
    id: '/manager/users',
    path: '/manager/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerWaiverTemplateRoute =
  AuthenticatedManagerWaiverTemplateRouteImport.update({
    id: '/manager/waiver-template',
    path: '/manager/waiver-template',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerWaiversRoute =
  AuthenticatedManagerWaiversRouteImport.update({
    id: '/manager/waivers',
    path: '/manager/waivers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiCalendarTokenRoute = ApiCalendarTokenRouteImport.update({
  id: '/api/calendar/$token',
  path: '/api/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManagerAgentRoute = ApiManagerAgentRouteImport.update({
  id: '/api/manager/agent',
  path: '/api/manager/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyEmailTokenRoute = ApiVerifyEmailTokenRouteImport.update({
  id: '/api/verify-email/$token',
  path: '/api/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManagerBlogIdRoute =
  AuthenticatedManagerBlogIdRouteImport.update({
    id: '/manager/blog_/$id',
    path: '/manager/blog/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerBlogNewRoute =
  AuthenticatedManagerBlogNewRouteImport.update({
    id: '/manager/blog_/new',
    path: '/manager/blog/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerUsersUserIdRoute =
  AuthenticatedManagerUsersUserIdRouteImport.update({
    id: '/manager/users_/$userId',
    path: '/manager/users/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerWaiversUploadRoute =
  AuthenticatedManagerWaiversUploadRouteImport.update({
    id: '/manager/waivers_/upload',
    path: '/manager/waivers/upload',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kb': typeof KbRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/classes': typeof ClassesRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/first-class': typeof FirstClassRoute
  '/instructors': typeof InstructorsRoute
  '/pricing': typeof PricingRoute
  '/register-interest': typeof RegisterInterestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/update-password': typeof UpdatePasswordRoute
  '/waiver': typeof WaiverRoute
  '/account': typeof AuthenticatedAccountRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/kb/$slug': typeof KbSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/kb/': typeof KbIndexRoute
  '/manager/api-tokens': typeof AuthenticatedManagerApiTokensRoute
  '/manager/blog': typeof AuthenticatedManagerBlogRoute
  '/manager/blog-comments': typeof AuthenticatedManagerBlogCommentsRoute
  '/manager/calendar': typeof AuthenticatedManagerCalendarRoute
  '/manager/check-in': typeof AuthenticatedManagerCheckInRoute
  '/manager/kb': typeof AuthenticatedManagerKbRoute
  '/manager/membership-plans': typeof AuthenticatedManagerMembershipPlansRoute
  '/manager/memberships': typeof AuthenticatedManagerMembershipsRoute
  '/manager/reconciliation': typeof AuthenticatedManagerReconciliationRoute
  '/manager/settings': typeof AuthenticatedManagerSettingsRoute
  '/manager/users': typeof AuthenticatedManagerUsersRoute
  '/manager/waiver-template': typeof AuthenticatedManagerWaiverTemplateRoute
  '/manager/waivers': typeof AuthenticatedManagerWaiversRoute
  '/api/calendar/$token': typeof ApiCalendarTokenRoute
  '/api/manager/agent': typeof ApiManagerAgentRoute
  '/api/verify-email/$token': typeof ApiVerifyEmailTokenRoute
  '/manager/': typeof AuthenticatedManagerIndexRoute
  '/manager/blog/$id': typeof AuthenticatedManagerBlogIdRoute
  '/manager/blog/new': typeof AuthenticatedManagerBlogNewRoute
  '/manager/users/$userId': typeof AuthenticatedManagerUsersUserIdRoute
  '/manager/waivers/upload': typeof AuthenticatedManagerWaiversUploadRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/classes': typeof ClassesRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/first-class': typeof FirstClassRoute
  '/instructors': typeof InstructorsRoute
  '/pricing': typeof PricingRoute
  '/register-interest': typeof RegisterInterestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/update-password': typeof UpdatePasswordRoute
  '/waiver': typeof WaiverRoute
  '/account': typeof AuthenticatedAccountRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/kb/$slug': typeof KbSlugRoute
  '/blog': typeof BlogIndexRoute
  '/kb': typeof KbIndexRoute
  '/manager/api-tokens': typeof AuthenticatedManagerApiTokensRoute
  '/manager/blog': typeof AuthenticatedManagerBlogRoute
  '/manager/blog-comments': typeof AuthenticatedManagerBlogCommentsRoute
  '/manager/calendar': typeof AuthenticatedManagerCalendarRoute
  '/manager/check-in': typeof AuthenticatedManagerCheckInRoute
  '/manager/kb': typeof AuthenticatedManagerKbRoute
  '/manager/membership-plans': typeof AuthenticatedManagerMembershipPlansRoute
  '/manager/memberships': typeof AuthenticatedManagerMembershipsRoute
  '/manager/reconciliation': typeof AuthenticatedManagerReconciliationRoute
  '/manager/settings': typeof AuthenticatedManagerSettingsRoute
  '/manager/users': typeof AuthenticatedManagerUsersRoute
  '/manager/waiver-template': typeof AuthenticatedManagerWaiverTemplateRoute
  '/manager/waivers': typeof AuthenticatedManagerWaiversRoute
  '/api/calendar/$token': typeof ApiCalendarTokenRoute
  '/api/manager/agent': typeof ApiManagerAgentRoute
  '/api/verify-email/$token': typeof ApiVerifyEmailTokenRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
  '/manager/blog/$id': typeof AuthenticatedManagerBlogIdRoute
  '/manager/blog/new': typeof AuthenticatedManagerBlogNewRoute
  '/manager/users/$userId': typeof AuthenticatedManagerUsersUserIdRoute
  '/manager/waivers/upload': typeof AuthenticatedManagerWaiversUploadRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/kb': typeof KbRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/classes': typeof ClassesRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/first-class': typeof FirstClassRoute
  '/instructors': typeof InstructorsRoute
  '/pricing': typeof PricingRoute
  '/register-interest': typeof RegisterInterestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/update-password': typeof UpdatePasswordRoute
  '/waiver': typeof WaiverRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/membership': typeof AuthenticatedMembershipRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/kb/$slug': typeof KbSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/kb/': typeof KbIndexRoute
  '/_authenticated/manager/api-tokens': typeof AuthenticatedManagerApiTokensRoute
  '/_authenticated/manager/blog': typeof AuthenticatedManagerBlogRoute
  '/_authenticated/manager/blog-comments': typeof AuthenticatedManagerBlogCommentsRoute
  '/_authenticated/manager/calendar': typeof AuthenticatedManagerCalendarRoute
  '/_authenticated/manager/check-in': typeof AuthenticatedManagerCheckInRoute
  '/_authenticated/manager/kb': typeof AuthenticatedManagerKbRoute
  '/_authenticated/manager/membership-plans': typeof AuthenticatedManagerMembershipPlansRoute
  '/_authenticated/manager/memberships': typeof AuthenticatedManagerMembershipsRoute
  '/_authenticated/manager/reconciliation': typeof AuthenticatedManagerReconciliationRoute
  '/_authenticated/manager/settings': typeof AuthenticatedManagerSettingsRoute
  '/_authenticated/manager/users': typeof AuthenticatedManagerUsersRoute
  '/_authenticated/manager/waiver-template': typeof AuthenticatedManagerWaiverTemplateRoute
  '/_authenticated/manager/waivers': typeof AuthenticatedManagerWaiversRoute
  '/api/calendar/$token': typeof ApiCalendarTokenRoute
  '/api/manager/agent': typeof ApiManagerAgentRoute
  '/api/verify-email/$token': typeof ApiVerifyEmailTokenRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
  '/_authenticated/manager/blog_/$id': typeof AuthenticatedManagerBlogIdRoute
  '/_authenticated/manager/blog_/new': typeof AuthenticatedManagerBlogNewRoute
  '/_authenticated/manager/users_/$userId': typeof AuthenticatedManagerUsersUserIdRoute
  '/_authenticated/manager/waivers_/upload': typeof AuthenticatedManagerWaiversUploadRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kb'
    | '/about'
    | '/app'
    | '/auth'
    | '/calendar'
    | '/classes'
    | '/code-of-conduct'
    | '/contact'
    | '/faq'
    | '/first-class'
    | '/instructors'
    | '/pricing'
    | '/register-interest'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/thank-you'
    | '/update-password'
    | '/waiver'
    | '/account'
    | '/membership'
    | '/blog/$slug'
    | '/kb/$slug'
    | '/blog/'
    | '/kb/'
    | '/manager/api-tokens'
    | '/manager/blog'
    | '/manager/blog-comments'
    | '/manager/calendar'
    | '/manager/check-in'
    | '/manager/kb'
    | '/manager/membership-plans'
    | '/manager/memberships'
    | '/manager/reconciliation'
    | '/manager/settings'
    | '/manager/users'
    | '/manager/waiver-template'
    | '/manager/waivers'
    | '/api/calendar/$token'
    | '/api/manager/agent'
    | '/api/verify-email/$token'
    | '/manager/'
    | '/manager/blog/$id'
    | '/manager/blog/new'
    | '/manager/users/$userId'
    | '/manager/waivers/upload'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/calendar'
    | '/classes'
    | '/code-of-conduct'
    | '/contact'
    | '/faq'
    | '/first-class'
    | '/instructors'
    | '/pricing'
    | '/register-interest'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/thank-you'
    | '/update-password'
    | '/waiver'
    | '/account'
    | '/membership'
    | '/blog/$slug'
    | '/kb/$slug'
    | '/blog'
    | '/kb'
    | '/manager/api-tokens'
    | '/manager/blog'
    | '/manager/blog-comments'
    | '/manager/calendar'
    | '/manager/check-in'
    | '/manager/kb'
    | '/manager/membership-plans'
    | '/manager/memberships'
    | '/manager/reconciliation'
    | '/manager/settings'
    | '/manager/users'
    | '/manager/waiver-template'
    | '/manager/waivers'
    | '/api/calendar/$token'
    | '/api/manager/agent'
    | '/api/verify-email/$token'
    | '/manager'
    | '/manager/blog/$id'
    | '/manager/blog/new'
    | '/manager/users/$userId'
    | '/manager/waivers/upload'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/kb'
    | '/about'
    | '/app'
    | '/auth'
    | '/calendar'
    | '/classes'
    | '/code-of-conduct'
    | '/contact'
    | '/faq'
    | '/first-class'
    | '/instructors'
    | '/pricing'
    | '/register-interest'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/thank-you'
    | '/update-password'
    | '/waiver'
    | '/_authenticated/account'
    | '/_authenticated/membership'
    | '/blog/$slug'
    | '/kb/$slug'
    | '/blog/'
    | '/kb/'
    | '/_authenticated/manager/api-tokens'
    | '/_authenticated/manager/blog'
    | '/_authenticated/manager/blog-comments'
    | '/_authenticated/manager/calendar'
    | '/_authenticated/manager/check-in'
    | '/_authenticated/manager/kb'
    | '/_authenticated/manager/membership-plans'
    | '/_authenticated/manager/memberships'
    | '/_authenticated/manager/reconciliation'
    | '/_authenticated/manager/settings'
    | '/_authenticated/manager/users'
    | '/_authenticated/manager/waiver-template'
    | '/_authenticated/manager/waivers'
    | '/api/calendar/$token'
    | '/api/manager/agent'
    | '/api/verify-email/$token'
    | '/_authenticated/manager/'
    | '/_authenticated/manager/blog_/$id'
    | '/_authenticated/manager/blog_/new'
    | '/_authenticated/manager/users_/$userId'
    | '/_authenticated/manager/waivers_/upload'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  KbRouteRoute: typeof KbRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  ClassesRoute: typeof ClassesRoute
  CodeOfConductRoute: typeof CodeOfConductRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FirstClassRoute: typeof FirstClassRoute
  InstructorsRoute: typeof InstructorsRoute
  PricingRoute: typeof PricingRoute
  RegisterInterestRoute: typeof RegisterInterestRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThankYouRoute: typeof ThankYouRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  WaiverRoute: typeof WaiverRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiCalendarTokenRoute: typeof ApiCalendarTokenRoute
  ApiManagerAgentRoute: typeof ApiManagerAgentRoute
  ApiVerifyEmailTokenRoute: typeof ApiVerifyEmailTokenRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-of-conduct': {
      id: '/code-of-conduct'
      path: '/code-of-conduct'
      fullPath: '/code-of-conduct'
      preLoaderRoute: typeof CodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-class': {
      id: '/first-class'
      path: '/first-class'
      fullPath: '/first-class'
      preLoaderRoute: typeof FirstClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb': {
      id: '/kb'
      path: '/kb'
      fullPath: '/kb'
      preLoaderRoute: typeof KbRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-interest': {
      id: '/register-interest'
      path: '/register-interest'
      fullPath: '/register-interest'
      preLoaderRoute: typeof RegisterInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiver': {
      id: '/waiver'
      path: '/waiver'
      fullPath: '/waiver'
      preLoaderRoute: typeof WaiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membership': {
      id: '/_authenticated/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof AuthenticatedMembershipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb/': {
      id: '/kb/'
      path: '/'
      fullPath: '/kb/'
      preLoaderRoute: typeof KbIndexRouteImport
      parentRoute: typeof KbRouteRoute
    }
    '/kb/$slug': {
      id: '/kb/$slug'
      path: '/$slug'
      fullPath: '/kb/$slug'
      preLoaderRoute: typeof KbSlugRouteImport
      parentRoute: typeof KbRouteRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/api-tokens': {
      id: '/_authenticated/manager/api-tokens'
      path: '/manager/api-tokens'
      fullPath: '/manager/api-tokens'
      preLoaderRoute: typeof AuthenticatedManagerApiTokensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/blog': {
      id: '/_authenticated/manager/blog'
      path: '/manager/blog'
      fullPath: '/manager/blog'
      preLoaderRoute: typeof AuthenticatedManagerBlogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/blog-comments': {
      id: '/_authenticated/manager/blog-comments'
      path: '/manager/blog-comments'
      fullPath: '/manager/blog-comments'
      preLoaderRoute: typeof AuthenticatedManagerBlogCommentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/calendar': {
      id: '/_authenticated/manager/calendar'
      path: '/manager/calendar'
      fullPath: '/manager/calendar'
      preLoaderRoute: typeof AuthenticatedManagerCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/check-in': {
      id: '/_authenticated/manager/check-in'
      path: '/manager/check-in'
      fullPath: '/manager/check-in'
      preLoaderRoute: typeof AuthenticatedManagerCheckInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/kb': {
      id: '/_authenticated/manager/kb'
      path: '/manager/kb'
      fullPath: '/manager/kb'
      preLoaderRoute: typeof AuthenticatedManagerKbRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/membership-plans': {
      id: '/_authenticated/manager/membership-plans'
      path: '/manager/membership-plans'
      fullPath: '/manager/membership-plans'
      preLoaderRoute: typeof AuthenticatedManagerMembershipPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/memberships': {
      id: '/_authenticated/manager/memberships'
      path: '/manager/memberships'
      fullPath: '/manager/memberships'
      preLoaderRoute: typeof AuthenticatedManagerMembershipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/reconciliation': {
      id: '/_authenticated/manager/reconciliation'
      path: '/manager/reconciliation'
      fullPath: '/manager/reconciliation'
      preLoaderRoute: typeof AuthenticatedManagerReconciliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/settings': {
      id: '/_authenticated/manager/settings'
      path: '/manager/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof AuthenticatedManagerSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/users': {
      id: '/_authenticated/manager/users'
      path: '/manager/users'
      fullPath: '/manager/users'
      preLoaderRoute: typeof AuthenticatedManagerUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/waiver-template': {
      id: '/_authenticated/manager/waiver-template'
      path: '/manager/waiver-template'
      fullPath: '/manager/waiver-template'
      preLoaderRoute: typeof AuthenticatedManagerWaiverTemplateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/waivers': {
      id: '/_authenticated/manager/waivers'
      path: '/manager/waivers'
      fullPath: '/manager/waivers'
      preLoaderRoute: typeof AuthenticatedManagerWaiversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/calendar/$token': {
      id: '/api/calendar/$token'
      path: '/api/calendar/$token'
      fullPath: '/api/calendar/$token'
      preLoaderRoute: typeof ApiCalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manager/agent': {
      id: '/api/manager/agent'
      path: '/api/manager/agent'
      fullPath: '/api/manager/agent'
      preLoaderRoute: typeof ApiManagerAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-email/$token': {
      id: '/api/verify-email/$token'
      path: '/api/verify-email/$token'
      fullPath: '/api/verify-email/$token'
      preLoaderRoute: typeof ApiVerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manager/blog_/$id': {
      id: '/_authenticated/manager/blog_/$id'
      path: '/manager/blog/$id'
      fullPath: '/manager/blog/$id'
      preLoaderRoute: typeof AuthenticatedManagerBlogIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/blog_/new': {
      id: '/_authenticated/manager/blog_/new'
      path: '/manager/blog/new'
      fullPath: '/manager/blog/new'
      preLoaderRoute: typeof AuthenticatedManagerBlogNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/users_/$userId': {
      id: '/_authenticated/manager/users_/$userId'
      path: '/manager/users/$userId'
      fullPath: '/manager/users/$userId'
      preLoaderRoute: typeof AuthenticatedManagerUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/waivers_/upload': {
      id: '/_authenticated/manager/waivers_/upload'
      path: '/manager/waivers/upload'
      fullPath: '/manager/waivers/upload'
      preLoaderRoute: typeof AuthenticatedManagerWaiversUploadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedMembershipRoute: typeof AuthenticatedMembershipRoute
  AuthenticatedManagerApiTokensRoute: typeof AuthenticatedManagerApiTokensRoute
  AuthenticatedManagerBlogRoute: typeof AuthenticatedManagerBlogRoute
  AuthenticatedManagerBlogCommentsRoute: typeof AuthenticatedManagerBlogCommentsRoute
  AuthenticatedManagerCalendarRoute: typeof AuthenticatedManagerCalendarRoute
  AuthenticatedManagerCheckInRoute: typeof AuthenticatedManagerCheckInRoute
  AuthenticatedManagerKbRoute: typeof AuthenticatedManagerKbRoute
  AuthenticatedManagerMembershipPlansRoute: typeof AuthenticatedManagerMembershipPlansRoute
  AuthenticatedManagerMembershipsRoute: typeof AuthenticatedManagerMembershipsRoute
  AuthenticatedManagerReconciliationRoute: typeof AuthenticatedManagerReconciliationRoute
  AuthenticatedManagerSettingsRoute: typeof AuthenticatedManagerSettingsRoute
  AuthenticatedManagerUsersRoute: typeof AuthenticatedManagerUsersRoute
  AuthenticatedManagerWaiverTemplateRoute: typeof AuthenticatedManagerWaiverTemplateRoute
  AuthenticatedManagerWaiversRoute: typeof AuthenticatedManagerWaiversRoute
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
  AuthenticatedManagerBlogIdRoute: typeof AuthenticatedManagerBlogIdRoute
  AuthenticatedManagerBlogNewRoute: typeof AuthenticatedManagerBlogNewRoute
  AuthenticatedManagerUsersUserIdRoute: typeof AuthenticatedManagerUsersUserIdRoute
  AuthenticatedManagerWaiversUploadRoute: typeof AuthenticatedManagerWaiversUploadRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedMembershipRoute: AuthenticatedMembershipRoute,
  AuthenticatedManagerApiTokensRoute: AuthenticatedManagerApiTokensRoute,
  AuthenticatedManagerBlogRoute: AuthenticatedManagerBlogRoute,
  AuthenticatedManagerBlogCommentsRoute: AuthenticatedManagerBlogCommentsRoute,
  AuthenticatedManagerCalendarRoute: AuthenticatedManagerCalendarRoute,
  AuthenticatedManagerCheckInRoute: AuthenticatedManagerCheckInRoute,
  AuthenticatedManagerKbRoute: AuthenticatedManagerKbRoute,
  AuthenticatedManagerMembershipPlansRoute:
    AuthenticatedManagerMembershipPlansRoute,
  AuthenticatedManagerMembershipsRoute: AuthenticatedManagerMembershipsRoute,
  AuthenticatedManagerReconciliationRoute:
    AuthenticatedManagerReconciliationRoute,
  AuthenticatedManagerSettingsRoute: AuthenticatedManagerSettingsRoute,
  AuthenticatedManagerUsersRoute: AuthenticatedManagerUsersRoute,
  AuthenticatedManagerWaiverTemplateRoute:
    AuthenticatedManagerWaiverTemplateRoute,
  AuthenticatedManagerWaiversRoute: AuthenticatedManagerWaiversRoute,
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
  AuthenticatedManagerBlogIdRoute: AuthenticatedManagerBlogIdRoute,
  AuthenticatedManagerBlogNewRoute: AuthenticatedManagerBlogNewRoute,
  AuthenticatedManagerUsersUserIdRoute: AuthenticatedManagerUsersUserIdRoute,
  AuthenticatedManagerWaiversUploadRoute:
    AuthenticatedManagerWaiversUploadRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface KbRouteRouteChildren {
  KbSlugRoute: typeof KbSlugRoute
  KbIndexRoute: typeof KbIndexRoute
}

const KbRouteRouteChildren: KbRouteRouteChildren = {
  KbSlugRoute: KbSlugRoute,
  KbIndexRoute: KbIndexRoute,
}

const KbRouteRouteWithChildren =
  KbRouteRoute._addFileChildren(KbRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  KbRouteRoute: KbRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  ClassesRoute: ClassesRoute,
  CodeOfConductRoute: CodeOfConductRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FirstClassRoute: FirstClassRoute,
  InstructorsRoute: InstructorsRoute,
  PricingRoute: PricingRoute,
  RegisterInterestRoute: RegisterInterestRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThankYouRoute: ThankYouRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  WaiverRoute: WaiverRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiCalendarTokenRoute: ApiCalendarTokenRoute,
  ApiManagerAgentRoute: ApiManagerAgentRoute,
  ApiVerifyEmailTokenRoute: ApiVerifyEmailTokenRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
