/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FirstClassRouteImport } from './routes/first-class'
import { Route as InstructorsRouteImport } from './routes/instructors'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RegisterInterestRouteImport } from './routes/register-interest'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as WaiverRouteImport } from './routes/waiver'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedMembershipRouteImport } from './routes/_authenticated/membership'
import { Route as AuthenticatedManagerApiTokensRouteImport } from './routes/_authenticated/manager.api-tokens'
import { Route as AuthenticatedManagerMembershipPlansRouteImport } from './routes/_authenticated/manager.membership-plans'
import { Route as AuthenticatedManagerMembershipsRouteImport } from './routes/_authenticated/manager.memberships'
import { Route as AuthenticatedManagerReconciliationRouteImport } from './routes/_authenticated/manager.reconciliation'
import { Route as AuthenticatedManagerSettingsRouteImport } from './routes/_authenticated/manager.settings'
import { Route as AuthenticatedManagerUsersRouteImport } from './routes/_authenticated/manager.users'
import { Route as AuthenticatedManagerWaiverTemplateRouteImport } from './routes/_authenticated/manager.waiver-template'
import { Route as AuthenticatedManagerWaiversRouteImport } from './routes/_authenticated/manager.waivers'
import { Route as ApiManagerAgentRouteImport } from './routes/api/manager/agent'
import { Route as AuthenticatedManagerUsersUserIdRouteImport } from './routes/_authenticated/manager.users_.$userId'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstClassRoute = FirstClassRouteImport.update({
  id: '/first-class',
  path: '/first-class',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorsRoute = InstructorsRouteImport.update({
  id: '/instructors',
  path: '/instructors',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterInterestRoute = RegisterInterestRouteImport.update({
  id: '/register-interest',
  path: '/register-interest',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiverRoute = WaiverRouteImport.update({
  id: '/waiver',
  path: '/waiver',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembershipRoute = AuthenticatedMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagerApiTokensRoute =
  AuthenticatedManagerApiTokensRouteImport.update({
    id: '/manager/api-tokens',
    path: '/manager/api-tokens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerMembershipPlansRoute =
  AuthenticatedManagerMembershipPlansRouteImport.update({
    id: '/manager/membership-plans',
    path: '/manager/membership-plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerMembershipsRoute =
  AuthenticatedManagerMembershipsRouteImport.update({
    id: '/manager/memberships',
    path: '/manager/memberships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerReconciliationRoute =
  AuthenticatedManagerReconciliationRouteImport.update({
    id: '/manager/reconciliation',
    path: '/manager/reconciliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerSettingsRoute =
  AuthenticatedManagerSettingsRouteImport.update({
    id: '/manager/settings',
    path: '/manager/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerUsersRoute =
  AuthenticatedManagerUsersRouteImport.update({
    id: '/manager/users',
    path: '/manager/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerWaiverTemplateRoute =
  AuthenticatedManagerWaiverTemplateRouteImport.update({
    id: '/manager/waiver-template',
    path: '/manager/waiver-template',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerWaiversRoute =
  AuthenticatedManagerWaiversRouteImport.update({
    id: '/manager/waivers',
    path: '/manager/waivers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiManagerAgentRoute = ApiManagerAgentRouteImport.update({
  id: '/api/manager/agent',
  path: '/api/manager/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManagerUsersUserIdRoute =
  AuthenticatedManagerUsersUserIdRouteImport.update({
    id: '/manager/users_/$userId',
    path: '/manager/users/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/first-class': typeof FirstClassRoute
  '/instructors': typeof InstructorsRoute
  '/pricing': typeof PricingRoute
  '/register-interest': typeof RegisterInterestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/thank-you': typeof ThankYouRoute
  '/update-password': typeof UpdatePasswordRoute
  '/waiver': typeof WaiverRoute
  '/account': typeof AuthenticatedAccountRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/manager/api-tokens': typeof AuthenticatedManagerApiTokensRoute
  '/manager/membership-plans': typeof AuthenticatedManagerMembershipPlansRoute
  '/manager/memberships': typeof AuthenticatedManagerMembershipsRoute
  '/manager/reconciliation': typeof AuthenticatedManagerReconciliationRoute
  '/manager/settings': typeof AuthenticatedManagerSettingsRoute
  '/manager/users': typeof AuthenticatedManagerUsersRoute
  '/manager/waiver-template': typeof AuthenticatedManagerWaiverTemplateRoute
  '/manager/waivers': typeof AuthenticatedManagerWaiversRoute
  '/api/manager/agent': typeof ApiManagerAgentRoute
  '/manager/users/$userId': typeof AuthenticatedManagerUsersUserIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/first-class': typeof FirstClassRoute
  '/instructors': typeof InstructorsRoute
  '/pricing': typeof PricingRoute
  '/register-interest': typeof RegisterInterestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/thank-you': typeof ThankYouRoute
  '/update-password': typeof UpdatePasswordRoute
  '/waiver': typeof WaiverRoute
  '/account': typeof AuthenticatedAccountRoute
  '/membership': typeof AuthenticatedMembershipRoute
  '/manager/api-tokens': typeof AuthenticatedManagerApiTokensRoute
  '/manager/membership-plans': typeof AuthenticatedManagerMembershipPlansRoute
  '/manager/memberships': typeof AuthenticatedManagerMembershipsRoute
  '/manager/reconciliation': typeof AuthenticatedManagerReconciliationRoute
  '/manager/settings': typeof AuthenticatedManagerSettingsRoute
  '/manager/users': typeof AuthenticatedManagerUsersRoute
  '/manager/waiver-template': typeof AuthenticatedManagerWaiverTemplateRoute
  '/manager/waivers': typeof AuthenticatedManagerWaiversRoute
  '/api/manager/agent': typeof ApiManagerAgentRoute
  '/manager/users/$userId': typeof AuthenticatedManagerUsersUserIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/first-class': typeof FirstClassRoute
  '/instructors': typeof InstructorsRoute
  '/pricing': typeof PricingRoute
  '/register-interest': typeof RegisterInterestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/thank-you': typeof ThankYouRoute
  '/update-password': typeof UpdatePasswordRoute
  '/waiver': typeof WaiverRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/membership': typeof AuthenticatedMembershipRoute
  '/_authenticated/manager/api-tokens': typeof AuthenticatedManagerApiTokensRoute
  '/_authenticated/manager/membership-plans': typeof AuthenticatedManagerMembershipPlansRoute
  '/_authenticated/manager/memberships': typeof AuthenticatedManagerMembershipsRoute
  '/_authenticated/manager/reconciliation': typeof AuthenticatedManagerReconciliationRoute
  '/_authenticated/manager/settings': typeof AuthenticatedManagerSettingsRoute
  '/_authenticated/manager/users': typeof AuthenticatedManagerUsersRoute
  '/_authenticated/manager/waiver-template': typeof AuthenticatedManagerWaiverTemplateRoute
  '/_authenticated/manager/waivers': typeof AuthenticatedManagerWaiversRoute
  '/api/manager/agent': typeof ApiManagerAgentRoute
  '/_authenticated/manager/users_/$userId': typeof AuthenticatedManagerUsersUserIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/classes'
    | '/contact'
    | '/faq'
    | '/first-class'
    | '/instructors'
    | '/pricing'
    | '/register-interest'
    | '/reset-password'
    | '/thank-you'
    | '/update-password'
    | '/waiver'
    | '/account'
    | '/membership'
    | '/manager/api-tokens'
    | '/manager/membership-plans'
    | '/manager/memberships'
    | '/manager/reconciliation'
    | '/manager/settings'
    | '/manager/users'
    | '/manager/waiver-template'
    | '/manager/waivers'
    | '/api/manager/agent'
    | '/manager/users/$userId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/classes'
    | '/contact'
    | '/faq'
    | '/first-class'
    | '/instructors'
    | '/pricing'
    | '/register-interest'
    | '/reset-password'
    | '/thank-you'
    | '/update-password'
    | '/waiver'
    | '/account'
    | '/membership'
    | '/manager/api-tokens'
    | '/manager/membership-plans'
    | '/manager/memberships'
    | '/manager/reconciliation'
    | '/manager/settings'
    | '/manager/users'
    | '/manager/waiver-template'
    | '/manager/waivers'
    | '/api/manager/agent'
    | '/manager/users/$userId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/classes'
    | '/contact'
    | '/faq'
    | '/first-class'
    | '/instructors'
    | '/pricing'
    | '/register-interest'
    | '/reset-password'
    | '/thank-you'
    | '/update-password'
    | '/waiver'
    | '/_authenticated/account'
    | '/_authenticated/membership'
    | '/_authenticated/manager/api-tokens'
    | '/_authenticated/manager/membership-plans'
    | '/_authenticated/manager/memberships'
    | '/_authenticated/manager/reconciliation'
    | '/_authenticated/manager/settings'
    | '/_authenticated/manager/users'
    | '/_authenticated/manager/waiver-template'
    | '/_authenticated/manager/waivers'
    | '/api/manager/agent'
    | '/_authenticated/manager/users_/$userId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ClassesRoute: typeof ClassesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FirstClassRoute: typeof FirstClassRoute
  InstructorsRoute: typeof InstructorsRoute
  PricingRoute: typeof PricingRoute
  RegisterInterestRoute: typeof RegisterInterestRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ThankYouRoute: typeof ThankYouRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  WaiverRoute: typeof WaiverRoute
  ApiManagerAgentRoute: typeof ApiManagerAgentRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-class': {
      id: '/first-class'
      path: '/first-class'
      fullPath: '/first-class'
      preLoaderRoute: typeof FirstClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructors': {
      id: '/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof InstructorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-interest': {
      id: '/register-interest'
      path: '/register-interest'
      fullPath: '/register-interest'
      preLoaderRoute: typeof RegisterInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiver': {
      id: '/waiver'
      path: '/waiver'
      fullPath: '/waiver'
      preLoaderRoute: typeof WaiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membership': {
      id: '/_authenticated/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof AuthenticatedMembershipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/api-tokens': {
      id: '/_authenticated/manager/api-tokens'
      path: '/manager/api-tokens'
      fullPath: '/manager/api-tokens'
      preLoaderRoute: typeof AuthenticatedManagerApiTokensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/membership-plans': {
      id: '/_authenticated/manager/membership-plans'
      path: '/manager/membership-plans'
      fullPath: '/manager/membership-plans'
      preLoaderRoute: typeof AuthenticatedManagerMembershipPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/memberships': {
      id: '/_authenticated/manager/memberships'
      path: '/manager/memberships'
      fullPath: '/manager/memberships'
      preLoaderRoute: typeof AuthenticatedManagerMembershipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/reconciliation': {
      id: '/_authenticated/manager/reconciliation'
      path: '/manager/reconciliation'
      fullPath: '/manager/reconciliation'
      preLoaderRoute: typeof AuthenticatedManagerReconciliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/settings': {
      id: '/_authenticated/manager/settings'
      path: '/manager/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof AuthenticatedManagerSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/users': {
      id: '/_authenticated/manager/users'
      path: '/manager/users'
      fullPath: '/manager/users'
      preLoaderRoute: typeof AuthenticatedManagerUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/waiver-template': {
      id: '/_authenticated/manager/waiver-template'
      path: '/manager/waiver-template'
      fullPath: '/manager/waiver-template'
      preLoaderRoute: typeof AuthenticatedManagerWaiverTemplateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/waivers': {
      id: '/_authenticated/manager/waivers'
      path: '/manager/waivers'
      fullPath: '/manager/waivers'
      preLoaderRoute: typeof AuthenticatedManagerWaiversRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/manager/agent': {
      id: '/api/manager/agent'
      path: '/api/manager/agent'
      fullPath: '/api/manager/agent'
      preLoaderRoute: typeof ApiManagerAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manager/users_/$userId': {
      id: '/_authenticated/manager/users_/$userId'
      path: '/manager/users/$userId'
      fullPath: '/manager/users/$userId'
      preLoaderRoute: typeof AuthenticatedManagerUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedMembershipRoute: typeof AuthenticatedMembershipRoute
  AuthenticatedManagerApiTokensRoute: typeof AuthenticatedManagerApiTokensRoute
  AuthenticatedManagerMembershipPlansRoute: typeof AuthenticatedManagerMembershipPlansRoute
  AuthenticatedManagerMembershipsRoute: typeof AuthenticatedManagerMembershipsRoute
  AuthenticatedManagerReconciliationRoute: typeof AuthenticatedManagerReconciliationRoute
  AuthenticatedManagerSettingsRoute: typeof AuthenticatedManagerSettingsRoute
  AuthenticatedManagerUsersRoute: typeof AuthenticatedManagerUsersRoute
  AuthenticatedManagerWaiverTemplateRoute: typeof AuthenticatedManagerWaiverTemplateRoute
  AuthenticatedManagerWaiversRoute: typeof AuthenticatedManagerWaiversRoute
  AuthenticatedManagerUsersUserIdRoute: typeof AuthenticatedManagerUsersUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedMembershipRoute: AuthenticatedMembershipRoute,
  AuthenticatedManagerApiTokensRoute: AuthenticatedManagerApiTokensRoute,
  AuthenticatedManagerMembershipPlansRoute:
    AuthenticatedManagerMembershipPlansRoute,
  AuthenticatedManagerMembershipsRoute: AuthenticatedManagerMembershipsRoute,
  AuthenticatedManagerReconciliationRoute:
    AuthenticatedManagerReconciliationRoute,
  AuthenticatedManagerSettingsRoute: AuthenticatedManagerSettingsRoute,
  AuthenticatedManagerUsersRoute: AuthenticatedManagerUsersRoute,
  AuthenticatedManagerWaiverTemplateRoute:
    AuthenticatedManagerWaiverTemplateRoute,
  AuthenticatedManagerWaiversRoute: AuthenticatedManagerWaiversRoute,
  AuthenticatedManagerUsersUserIdRoute: AuthenticatedManagerUsersUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ClassesRoute: ClassesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FirstClassRoute: FirstClassRoute,
  InstructorsRoute: InstructorsRoute,
  PricingRoute: PricingRoute,
  RegisterInterestRoute: RegisterInterestRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ThankYouRoute: ThankYouRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  WaiverRoute: WaiverRoute,
  ApiManagerAgentRoute: ApiManagerAgentRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
