-- Intentionally a no-op. Kept as a file so the applied-migration ledger stays
-- intact; do not delete it and do not re-add the statements below.
--
-- This migration arrived with a Lovable "Rebuilt schema cache" edit
-- (commit 6b2d32a, 2026-07-25) and was a verbatim duplicate of
-- 20260723000000_profiles.sql, which was already on main at the time: the same
-- CREATE TABLE public.profiles, the same policies, ensure_profile trigger,
-- user_id_by_email / user_emails helpers, and the same waivers reshape
-- (TRUNCATE, column drops, the ip_hash -> signer_ip rename). Only the comments
-- differed. Lovable generates migrations from the live database's schema rather
-- than from this directory's history, so a hand-written migration it later
-- re-derives can reappear here as a second copy.
--
-- Replaying the history onto an empty database therefore aborted on the second
-- CREATE TABLE with `relation "profiles" already exists` (SQLSTATE 42P07), so
-- `supabase db start` never finished and the Advisors / plpgsql_check job in
-- .github/workflows/supabase-lint.yml could not run at all. Making just the
-- CREATE TABLE idempotent is not enough -- every following statement collides
-- the same way (the policies, the trigger, the duplicate signer_meta and
-- user_id columns), and the rename has no old column left to rename.
--
-- Emptying the file is safe in both directions:
--   * Live: this migration is already recorded as applied, so its contents are
--     never re-run there. The schema is unchanged.
--   * From scratch: 20260723000000_profiles.sql alone builds exactly the same
--     objects, so the replayed schema is unchanged too.
--
-- See issue #53.

-- Retained from the original file: harmless, idempotent, and the reason the
-- edit existed at all -- it tells PostgREST to pick up the reshaped schema.
NOTIFY pgrst, 'reload schema';
